package tk.mybatis.simple.generator.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table train_manager_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TrainManagerInfo {
    /**
     * Database Column Remarks:
     *   逻辑主键,记录的唯一索引字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   机构员工编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.CCB_EMP_ID
     *
     * @mbggenerated
     */
    private String ccbEmpId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.EMPE_NM
     *
     * @mbggenerated
     */
    private String empeNm;

    /**
     * Database Column Remarks:
     *   人员编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   UAAP员工账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.EMPE_ID_LAND_NM
     *
     * @mbggenerated
     */
    private String empeIdLandNm;

    /**
     * Database Column Remarks:
     *   联系方式1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.CONTACT_INFO_1
     *
     * @mbggenerated
     */
    private String contactInfo1;

    /**
     * Database Column Remarks:
     *   联系方式2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.CONTACT_INFO_2
     *
     * @mbggenerated
     */
    private String contactInfo2;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.LAST_UDT_TIME
     *
     * @mbggenerated
     */
    private Date lastUdtTime;

    /**
     * Database Column Remarks:
     *   基地编号ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_manager_info.TRAININST_ID
     *
     * @mbggenerated
     */
    private String traininstId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.ID
     *
     * @return the value of train_manager_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.ID
     *
     * @param id the value for train_manager_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.CCB_EMP_ID
     *
     * @return the value of train_manager_info.CCB_EMP_ID
     *
     * @mbggenerated
     */
    public String getCcbEmpId() {
        return ccbEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.CCB_EMP_ID
     *
     * @param ccbEmpId the value for train_manager_info.CCB_EMP_ID
     *
     * @mbggenerated
     */
    public void setCcbEmpId(String ccbEmpId) {
        this.ccbEmpId = ccbEmpId == null ? null : ccbEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.EMPE_NM
     *
     * @return the value of train_manager_info.EMPE_NM
     *
     * @mbggenerated
     */
    public String getEmpeNm() {
        return empeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.EMPE_NM
     *
     * @param empeNm the value for train_manager_info.EMPE_NM
     *
     * @mbggenerated
     */
    public void setEmpeNm(String empeNm) {
        this.empeNm = empeNm == null ? null : empeNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.USER_ID
     *
     * @return the value of train_manager_info.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.USER_ID
     *
     * @param userId the value for train_manager_info.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.EMPE_ID_LAND_NM
     *
     * @return the value of train_manager_info.EMPE_ID_LAND_NM
     *
     * @mbggenerated
     */
    public String getEmpeIdLandNm() {
        return empeIdLandNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.EMPE_ID_LAND_NM
     *
     * @param empeIdLandNm the value for train_manager_info.EMPE_ID_LAND_NM
     *
     * @mbggenerated
     */
    public void setEmpeIdLandNm(String empeIdLandNm) {
        this.empeIdLandNm = empeIdLandNm == null ? null : empeIdLandNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.CONTACT_INFO_1
     *
     * @return the value of train_manager_info.CONTACT_INFO_1
     *
     * @mbggenerated
     */
    public String getContactInfo1() {
        return contactInfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.CONTACT_INFO_1
     *
     * @param contactInfo1 the value for train_manager_info.CONTACT_INFO_1
     *
     * @mbggenerated
     */
    public void setContactInfo1(String contactInfo1) {
        this.contactInfo1 = contactInfo1 == null ? null : contactInfo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.CONTACT_INFO_2
     *
     * @return the value of train_manager_info.CONTACT_INFO_2
     *
     * @mbggenerated
     */
    public String getContactInfo2() {
        return contactInfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.CONTACT_INFO_2
     *
     * @param contactInfo2 the value for train_manager_info.CONTACT_INFO_2
     *
     * @mbggenerated
     */
    public void setContactInfo2(String contactInfo2) {
        this.contactInfo2 = contactInfo2 == null ? null : contactInfo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.CREATE_TIME
     *
     * @return the value of train_manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.CREATE_TIME
     *
     * @param createTime the value for train_manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.LAST_UDT_TIME
     *
     * @return the value of train_manager_info.LAST_UDT_TIME
     *
     * @mbggenerated
     */
    public Date getLastUdtTime() {
        return lastUdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.LAST_UDT_TIME
     *
     * @param lastUdtTime the value for train_manager_info.LAST_UDT_TIME
     *
     * @mbggenerated
     */
    public void setLastUdtTime(Date lastUdtTime) {
        this.lastUdtTime = lastUdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_manager_info.TRAININST_ID
     *
     * @return the value of train_manager_info.TRAININST_ID
     *
     * @mbggenerated
     */
    public String getTraininstId() {
        return traininstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_manager_info.TRAININST_ID
     *
     * @param traininstId the value for train_manager_info.TRAININST_ID
     *
     * @mbggenerated
     */
    public void setTraininstId(String traininstId) {
        this.traininstId = traininstId == null ? null : traininstId.trim();
    }
}