package tk.mybatis.simple.generator.dao;

import java.util.List;
import tk.mybatis.simple.generator.model.SysRolePrivilege;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    List<SysRolePrivilege> selectAll();
}