package tk.mybatis.simple.generator.dao;

import java.util.List;
import tk.mybatis.simple.generator.model.TrainManagerInfo;

public interface TrainManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_manager_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_manager_info
     *
     * @mbggenerated
     */
    int insert(TrainManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_manager_info
     *
     * @mbggenerated
     */
    TrainManagerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_manager_info
     *
     * @mbggenerated
     */
    List<TrainManagerInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_manager_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrainManagerInfo record);
}